version: '3'
services:
  web:
    build: ./messenger
    ports:
      - "4500:4500"
    links:
      - db
  db:
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
